sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
  - rust: nightly

cache: cargo

env:
  - TEST_DIR=client
  - TEST_DIR=proto
  - TEST_DIR=server
before_script:
  - command -v cargo-coveralls > /dev/null 2>&1 || cargo install cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script: cd $TEST_DIR && echo $TRAVIS_RUST_VERSION && cargo build --verbose && cargo test --verbose

after_success:
  - cd .. && test $TEST_DIR = "proto" && test $TRAVIS_RUST_VERSION = "stable" &&
    cargo coveralls --verbose

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
