[package]
name = "xmpp-rs"
version = "0.1.2"
description = "A work in progress xmpp lib"
license = "MPL-2.0"
documentation = "https://docs.rs/xmpp-rs"
authors = ["Freyskeyd <simon.paitrault@iadvize.com>"]

[lib]
name = "xmpp"
path = "src/lib.rs"

[dev-dependencies]
elementtree = {git = "https://github.com/Freyskeyd/elementtree-rust"}
env_logger = "0"
futures = "0.1"
log = "0"
tokio-core = "0.1"
xml-rs = {git = "https://github.com/Freyskeyd/xml-rs"}

[dependencies.xmpp-proto]
path = "./proto"
version = "0"

[dependencies.xmpp-derive]
path = "./derive"
version = "0"

[dependencies.xmpp-client]
path = "./client"
version = "0"

[workspace]
members = ["client/", "proto/", "server/", "derive/"]

