[package]
name = "xmpp-derive"
version = "0.1.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]
[lib]
proc-macro = true
[dependencies]
syn = {version = "0.11.10", features = ["full"]}
quote = "0.3.15"
xmpp-proto = "0"
serde_codegen_internals = "0.14.2"
