[package]
name = "xmpp-proto"
version = "0.1.2"
description = "A work in progress xmpp lib"
license = "MPL-2.0"
documentation = "https://docs.rs/xmpp-proto"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]

[dependencies]
base64 = "0"
bytes = "0"
circular = "0"
elementtree = {git = "https://github.com/Freyskeyd/elementtree-rust"}
futures = "0"
log = "0"
native-tls = "0"
tokio-core = "0"
tokio-io = "0"
tokio-tls = "0.1.2"
uuid = { version = "0.4", features = ["v4"] }
xml-rs = {git = "https://github.com/Freyskeyd/xml-rs"}
xmpp-derive = {path = "../derive" }
sasl = "0.4.1"
clippy = {version = "*", optional = true}

[features]
default = []
lint = ["clippy"]
